Fixed. `rake new_cop` doesn't work since rubocop v1.22.0
```
$ bundle exec rake new_cop[Foo/Bar]
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
/path/to/my-cop/vendor/bundle/ruby/3.1.0/gems/rubocop-1.24.1/lib/rubocop/cop/generator.rb:114:in `initialize'
/path/to/my-cop/Rakefile:30:in `new'
/path/to/my-cop/Rakefile:30:in `block in <top (required)>'
/path/to/my-cop/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/sue445/.rbenv/versions/3.1.0/bin/bundle:23:in `load'
/Users/sue445/.rbenv/versions/3.1.0/bin/bundle:23:in `<main>'
Tasks: TOP => new_cop
(See full trace by running task with --trace)
```

c.f. https://github.com/rubocop/rubocop/pull/10109